services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: schedules
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      TZ: Europe/Kaliningrad
    ports:
      - "8080:8080"
      - "12345:12345"
    depends_on:
      - db

volumes:
  postgres_data: